about:
    license: MIT
    summary: Ectyper is a python script for serotyping e.coli genomes
    author: Camille La Rose, Chad Laing, Sam Sung
    home: https://github.com/phac-nml/ecoli_serotyping

package:
    name: ectyper
    version: 0.0.8

source:
    url: https://github.com/phac-nml/ecoli_serotyping/archive/0dbfb220d76f7c0fe840ed7c304d8cc1f6e994db.zip
    md5: f8224d2eaaee80b0797b7be9a26319ee

requirements:
    build:
        - python 3.6.3.*
    run:
        - python 3.6.3.*
        - pandas 0.21.0.*
        - samtools 1.5.*
        - bowtie2 2.3.0.*
        - mash 1.1.*
        - bcftools 1.6.*
        - biopython 1.69.*
        - blast 2.2.31 .*
        - seqtk 1.2.*
test:
    commands:
        - ectyper -h
